# Generated by Django 4.2.6 on 2024-01-30 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_privatechatroom_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="privatechatroom",
            name="connected_users",
            field=models.ManyToManyField(
                blank=True, related_name="connected_users", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="UnreadMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("count", models.IntegerField(default=0)),
                (
                    "recent_message",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chat.privatechatroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
